### ISSUE TITLE
Can we use voxvision on mobile devices?

### ISSUE THREAD

**Issue by codingwatching** [shamazmazum/voxvision#2]
Hi @shamazmazum 
Can we build voxvision for android, ios devices?
Thank you so much for creating such an awesome engine for the voxel game!

**Comment by shamazmazum** [comment]
Hi! I doubt that. The goal was to make a voxel renderer which works entirely on CPU. Hence you need a good multicore CPU for voxvision to work. I have no experience in developing android apps, but I think you need to rely on OpenGL on that platform.

Also voxvision is not a game engine, it's just a renderer with lua scripting for scene creation and input handling. A scene can only have one octree which is not suitable for a game.

**Comment by codingwatching** [comment]
Hi @shamazmazum Thank you for the detail explaination
Happy coding!
